sudo: false
language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
before_script:
  - go get golang.org/x/lint/golint
script:
  - cd hcloud
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
  - golint -set_exit_status ./...
  - go test ./...